EXP_NAME: MemSeg
SEED: 42

DATASET:
  datadir: '/datasets/MVTec'
  texture_source_dir: '/datasets/dtd/images'
  target: 'capsule'
  resize: !!python/tuple
    - 256 # height
    - 256 # width
  structure_grid_size: 8
  transparency_range:
    - 0.15 # under bound
    - 1. # upper bound
  perlin_scale: 6
  min_perlin_scale: 0
  perlin_noise_threshold: 0.5

DATALOADER:
  batch_size: 8
  num_workers: 0

MEMORYBANK:
  nb_memory_sample: 30

MODEL:
  feature_extractor_name: 'resnet18'

TRAIN:
  batch_size: 8
  num_training_steps: 2700
  l1_weight: 0.6
  focal_weight: 0.4
  focal_alpha: null
  focal_gamma: 4
  use_wandb: True

OPTIMIZER:
  lr: 0.04
  weight_decay: 0.0005

SCHEDULER:
  min_lr: 0.0001
  warmup_ratio: 0.1
  use_scheduler: False

LOG:
  log_interval: 1
  eval_interval: 100

RESULT:
  savedir: './saved_model'